[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
optimizer = true
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.default.optimizer_details]
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
