name: test

on:
  - workflow_dispatch
  - push

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/cache@v3
        with:
          path: "~/.foundry/cache/rpc"
          key: "${{ runner.os }}-rpc-cache-v1"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install yarn dependencies
        run: yarn

      - name: Check prettier
        run: yarn prettier:check

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --fork-url=${{secrets.NODE}} --fork-block-number=37610791
        id: test
  coverage:
    name: Foundry coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/cache@v3
        with:
          path: "~/.foundry/cache/rpc"
          key: "${{ runner.os }}-rpc-cache-v1"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge coverage
        run: |
          forge coverage -vvv --fork-url=${{secrets.NODE}} --fork-block-number=37610791 --report lcov --report summary
        id: coverage

      - name: Sanitize lcov report
        run: |
          sudo apt install lcov
          lcov --remove ./lcov.info -o ./clean_lcov.info 'test/*' 'src/script/*'
          lcov --list clean_lcov.info

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v2
        with:
          coverage-files: ./clean_lcov.info
          artifact-name: solidity-coverage-report
          working-directory: ./
